### ISSUE TITLE
lateinit property has not been initialized

### ISSUE THREAD

**Issue by alexxxdev** [oleksiyp/mockk#47]
I have this code:
```
interface IFoo

class Foo:IFoo {
	fun method(){
		// ...
	}
}

abstract class AbstractBar<T:IFoo>{
    @Inject
    lateinit var foo: T
}



class Bar: AbstractBar<Foo>() {
    fun call(){
        foo.method()
    }
}

class Test {
    @MockK
    lateinit var foo: Foo

    @InjectMockKs lateinit var bar: Bar

    @Before
    fun setUp() = MockKAnnotations.init(this)


    @Test
    fun test() {
        every { foo.method() } answers { nothing }
        bar.call()
        verify { foo.method() }
    }
}
```
and it produces an error:
`kotlin.UninitializedPropertyAccessException: lateinit property foo has not been initialized`

mockk version: 1.7.12

What do I need to do to get it right? or is it a bug?

**Comment by oleksiyp** [comment]
Think it is a bug. Will check in the evening why it is happening. Thanks

**Comment by oleksiyp** [comment]
Fixed in 1.7.13. Should be synced soon in maven repo. Github autoclosed ticket

**Comment by du-it** [comment]
I think this bug is back? I am using Kotlin 1.4.10 with MockK 1.10.2:

`kotlin.UninitializedPropertyAccessException: lateinit property myService has not been initialized`

Tried with @SpringBootTest

```
    @InjectMockKs
    @Autowired
    private lateinit var impl: MyService
```

I also tried with constructor initialization but this fails with an exception that exactly on no-arg constructor is required.
